[theme]
primaryColor = '#7792E3'
backgroundColor = '#273346'
secondaryBackgroundColor = 'black'
textColor = '#FFFFFF'
font = "sans serif"

[server]
port = 8502
enableStaticServing = true

[browser]
gatherUsageStats = false
